### ISSUE TITLE
dylib failed to load dynamic library on windows 10

### ISSUE THREAD

**Issue by hujinlong** [jpnurmi/dart_serial_port#32]
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (126)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      dylib (package:dart_serial_port/src/dylib.dart:32:54)
#3      _SerialPortImpl.availablePorts.<anonymous closure> (package:dart_serial_port/src/port.dart:230:32)
#4      Util.call (package:dart_serial_port/src/util.dart:37:21)
#5      _SerialPortImpl.availablePorts (package:dart_serial_port/src/port.dart:230:21)
#6      SerialPort.availablePorts (package:dart_serial_port/src/port.dart:82:61)
#7      main (package:fwst/main.dart:11:33)
#8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:140:25)
#9      _rootRun (dart:async/zone.dart:1354:13)
#10     _CustomZone.run (dart:async/zone.dart:1258:19)
#11     _runZoned (dart:async/zone.dart:1788:10)
#12     runZonedGuarded (dart:async/zone.dart:1776:12)
#13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:133:5)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by jpnurmi** [comment]
https://github.com/jpnurmi/flutter_serial_port
